### ISSUE TITLE
Could not download action repository 

### ISSUE THREAD

**Issue by hjohns12** [jroehl/gsheet.action#123]
**Describe the bug**
I tried to use the latest version of gsheet.action. I set it up with the following code: 

```
      - name: gsheet.action
        uses: jroehl/gsheet.action@v1.1.0
```

This is the error I received: 

Error: Could not find file '/home/runner/work/_actions/_temp_3c52df1b-b322-46f5-8a1d-8c702825ef00/_staging/jroehl-gsheet.action-310b822/node_modules/.bin/marked'.

**Additional context**
```
  build:
    runs-on: ubuntu-latest
```

**Comment by jroehl** [comment]
Hi, as far as I can tell did the E2E tests pass on the recent build. 🤔 
Can you share the complete `.yml` setup file you're using?

**Comment by hjohns12** [comment]
https://github.com/uclalawcovid19behindbars/compassionate-release-denials/blob/main/.github/workflows/main.yml 

Does this help? If you need to see more detailed info about what I have inside of the `secrets`, let me know.

**Comment by mmagician** [comment]
I get the same above error when running the example workflow with the newest version. 
It seems to work with v1.0.0 though

**Comment by jroehl** [comment]
Hi @hjohns12, sorry for the late reply - the issue is resolved in all marketplace versions of the action.
It was an issue with the build pipeline missing dependencies.
