### ISSUE TITLE
Error: Label has to be uppercase alphabet letter but is "0"

### ISSUE THREAD

**Issue by Yzuriha** [jroehl/gsheet.action#369]
**Describe the bug**
getData with range failfs if the number contains a 0

**To Reproduce**
E.g. do
` { "command": "getData",
      "args": {
        "range": "Blog!A10:F101"
      }
    }`

**Expected behavior**
It should recognize the range as a number.

**Error Message**
Error: Label has to be uppercase alphabet letter but is "0"

**Comment by leecalcote** [comment]
I'm running into this same issue.
