### ISSUE TITLE
variables inside the commands json 

### ISSUE THREAD

**Issue by mohamed-Dhia** [jroehl/gsheet.action#53]
Hey there, first of all, thanks a ton for this action, it has saved me a lot of time.
I need to replace the 1 in !B1 with and GitHub env variable is that possible? 
if not can you suggest a workaround if you can? 
```commands: |
	[
		{ "command": "getWorksheet", "args": { "worksheetTitle": "Sheet1" }},
		{ "command": "getData", "args": { "range": `"Sheet1'!B1" }}
	]
```

**Comment by 0x2b3bfa0** [comment]
@mohamed-Dhia, you can do that easily (replace `steps.example` with your variable):
```json
[
   {
      "command":"getWorksheet",
      "args":{
         "worksheetTitle":"Sheet1"
      }
   },
   {
      "command":"getData",
      "args":{
         "range":"Sheet1'!B${{ steps.example }}"
      }
   }
]
```
