### ISSUE TITLE
cannot use the getData function

### ISSUE THREAD

**Issue by AaronAbuUsama** [jroehl/gsheet.action#7]
Firstly, this is an awesome action. and this is not a bug, however, the documentation is a bit opaque with regards to

| name  | address | id  |
| ----- | ------- | --- |
| Alace | 0x1234  | 1   |
| Bob   | 0x2345  | 2   |

I want to get the Alice and bob row, ive tried

```
    { "command": "addWorksheet", "args": { "worksheetTitle": "test sheet" }},
    { "command": "getData", "args": { "minRow": 1 }, { "minCol": 1 }, {"maxRow": 2}, {"maxCol": 2}},
```
```
    { "command": "addWorksheet", "args": { "worksheetTitle": "test sheet" }},
    { "command": "getData", "args": { "minRow": 1 }, { "minCol": 1 }},
```
```
    { "command": "addWorksheet", "args": { "worksheetTitle": "test sheet" }},
    { "command": "getData", "args": { "minRow": 1 }, { "minCol": 1 }, {"range": "a2:c3"}},
```
```
    { "command": "addWorksheet", "args": { "worksheetTitle": "test sheet" }},
    { "command": "getData", "args": {"range": "a2:c3"}},
```

every time i get the same error `##[error]error:0909006C:PEM routines:get_name:no start line`

**Comment by jroehl** [comment]
Hi @pythonpete32, I am glad you like it 🙂

Could it be that you're trying to load the credentials from a file? This sounds to me like a formatting issue of the private key. 

About the documentation - I am always open to suggestions - open a PR if you like!

**Comment by AaronAbuUsama** [comment]
I am passing the credentials in as a GitHub secret, Thanks for pointing me in the direction to look.
given this table what would the syntax be if I want to return Alice and Bobs records?
| name  | address | id  |
| ----- | ------- | --- |
| Alace | 0x1234  | 1   |
| Bob   | 0x2345  | 2   |

and for sure, I'll open a or when I get it working :)

**Comment by jroehl** [comment]
You should be able to use either 
```json
{ "command": "addWorksheet", "args": { "worksheetTitle": "test sheet" }},
{ "command": "getData", "args": { "range": "'test sheet'!A2:B3" } }
```
or 
```json
{ "command": "addWorksheet", "args": { "worksheetTitle": "test sheet" }},
{ "command": "getData", "args": { "worksheetTitle": "test sheet", "minCol": 1, "minRow": 2, "maxCol": 3, "maxRow": 3} }
```
> You have to specify the `worksheetTitle` to  access the data of a specific worksheet.

I hope this helps.

**Comment by mohamed-Dhia** [comment]
hi I'm facing the same error `##[error]error:0909006C:PEM routines:get_name:no start line`
can anyone provide a small clarification 
thanks in advance❤
